/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MrChiSim */

#ifndef _Included_MrChiSim
#define _Included_MrChiSim
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MrChiSim
 * Method:    doFPGA
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MrChiSim_doFPGA
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     MrChiSim
 * Method:    create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MrChiSim_create
  (JNIEnv *, jclass);

/*
 * Class:     MrChiSim
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MrChiSim_destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
